services:
  api:
    container_name: planner_api
    build:
      context: .
      dockerfile: ./api/Dockerfile.prod
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}"
      DIRECT_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    ports:
      - "3000:3000"
    networks:
      - db_network
    depends_on:
      - database
    restart: always

  database:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: always

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge