-- DropForeignKey
ALTER TABLE "EVENTS_USERS" DROP CONSTRAINT "EVENTS_USERS_event_id_fkey";

-- DropForeignKey
ALTER TABLE "EVENTS_USERS" DROP CONSTRAINT "EVENTS_USERS_user_id_fkey";

-- DropForeignKey
ALTER TABLE "EVENT_COMMENTS" DROP CONSTRAINT "EVENT_COMMENTS_event_id_fkey";

-- DropForeignKey
ALTER TABLE "EVENT_COMMENTS" DROP CONSTRAINT "EVENT_COMMENTS_user_id_fkey";

-- DropForeignKey
ALTER TABLE "EVENT_LINKS" DROP CONSTRAINT "EVENT_LINKS_event_id_fkey";

-- AlterTable
ALTER TABLE "EVENT_COMMENTS" ALTER COLUMN "user_id" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "EVENTS_USERS" ADD CONSTRAINT "EVENTS_USERS_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "EVENTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTS_USERS" ADD CONSTRAINT "EVENTS_USERS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT_LINKS" ADD CONSTRAINT "EVENT_LINKS_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "EVENTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT_COMMENTS" ADD CONSTRAINT "EVENT_COMMENTS_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "EVENTS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT_COMMENTS" ADD CONSTRAINT "EVENT_COMMENTS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
