-- CreateTable
CREATE TABLE "EVENTS" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "date" TIMESTAMP(3),
    "time_in_seconds" INTEGER NOT NULL,
    "address" TEXT,

    CONSTRAINT "EVENTS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EVENTS_USERS" (
    "id" SERIAL NOT NULL,
    "event_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "role" TEXT NOT NULL,
    "status" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EVENTS_USERS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EVENT_LINKS" (
    "id" SERIAL NOT NULL,
    "event_id" INTEGER NOT NULL,
    "link" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EVENT_LINKS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EVENT_COMMENTS" (
    "id" SERIAL NOT NULL,
    "event_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "comment" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EVENT_COMMENTS_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "EVENTS_USERS" ADD CONSTRAINT "EVENTS_USERS_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "EVENTS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTS_USERS" ADD CONSTRAINT "EVENTS_USERS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT_LINKS" ADD CONSTRAINT "EVENT_LINKS_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "EVENTS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT_COMMENTS" ADD CONSTRAINT "EVENT_COMMENTS_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "EVENTS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENT_COMMENTS" ADD CONSTRAINT "EVENT_COMMENTS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
